spring:
  application:
    name: company-registry-service
  liquibase:
    changelog: classpath:config/liquibase/master.yaml
  profiles:
    active:
  jackson:
    serialization:
      indent-output: true
  # ===================================================================
  # Datasource
  # ===================================================================
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/CompanyRegistry
    username: CompanyRegistry
    name:
    password:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate


server:
  port: 8085
  servlet:
    context-path: /api
  tomcat:
    max-threads: 20
logging:
  level:
    ROOT: INFO
    com.incode: INFO
