databaseChangeLog:
  - changeSet:
      id: create-free-company-table-122
      author: aleksandar.nikolic
      changes:
       # - createSequence:
      #      sequenceName: free_company_id_seq
      #      incrementBy: 1
     #       startValue: 1
        - createTable:
            tableName: free_company
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: cin
                  type: VARCHAR
                  constraints:
                    nullable: false
              - column:
                  name: name
                  type: VARCHAR
                  constraints:
                    nullable: false
              - column:
                  name: registration_date
                  type: date
                  constraints:
                    nullable: false
              - column:
                  name: address
                  type: VARCHAR
                  constraints:
                    nullable: false
              - column:
                  name: is_active
                  type: BOOLEAN
                  constraints:
                    nullable: false
              - column:
                  name: created_time
                  type: TIMESTAMP
                  constraints:
                    nullable: false
              - column:
                  name: updated_time
                  type: TIMESTAMP
                  constraints:
                    nullable: true
        - createIndex:
            tableName: free_company
            indexName: idx_free_cin
            columns:
              - column:
                  name: cin
